version: "3.2"

services:
 nginx:
   image: nginx:alpine
   volumes:
     - ./var/www:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
   ports:
     - 80:80
     - 443:443
   depends_on:
     - php

 php:
   build:
     context: .
   volumes:
     - ./var/www:/var/www
   ports:
     - 9000:9000
   depends_on:
     - db
     
  db:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lab_laravel
      MYSQL_ROOT_PASSWORD: root   
      
  memcached:
    image: memcached
    container_name: base-memcached
    ports:
      - 11111:11111   